create table if not exists public.waiter_calls (
  id bigint generated by default as identity primary key,
  table_id text not null,
  request_type text not null check (request_type in ('assistance', 'payment')),
  note text not null default '',
  status text not null default 'pending' check (status in ('pending', 'handled')),
  fingerprint text,
  idempotency_key text,
  handled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists waiter_calls_status_created_idx
  on public.waiter_calls (status, created_at desc);

create index if not exists waiter_calls_table_created_idx
  on public.waiter_calls (table_id, created_at desc);

alter table public.waiter_calls enable row level security;

-- Customer devices can insert waiter calls.
drop policy if exists "waiter_calls_insert_anon" on public.waiter_calls;
create policy "waiter_calls_insert_anon"
on public.waiter_calls
for insert
to anon
with check (status = 'pending');

-- Staff dashboards can read pending/handled calls.
drop policy if exists "waiter_calls_select_anon" on public.waiter_calls;
create policy "waiter_calls_select_anon"
on public.waiter_calls
for select
to anon
using (true);

-- Staff dashboards can update call status to handled.
drop policy if exists "waiter_calls_update_anon" on public.waiter_calls;
create policy "waiter_calls_update_anon"
on public.waiter_calls
for update
to anon
using (true)
with check (status in ('pending', 'handled'));
